In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

# Logistic Regression

In [3]:
lr = LogisticRegression(solver='liblinear', multi_class='ovr')
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9611111111111111

# SVM

In [4]:
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.39166666666666666

# Random Forest

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9638888888888889

# KFold Cross Validation

Basic Example

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Use KFold for our digits example

In [8]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x_train, x_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

In [10]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [11]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [12]:
scores_rf

[0.9332220367278798, 0.9482470784641068, 0.9198664440734557]

# cross_val_score function

In [13]:
from sklearn.model_selection import cross_val_score

Logistic regression model performance using cross_val_score

In [17]:
cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

svm model performance using cross_val_score

In [18]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

random forest performance using cross_val_score

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.91652755, 0.95993322, 0.93155259])

cross_val_score uses stratified Kfold by default

# Parameter tunning using k fold cross validation

In [21]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8753289882060832

In [23]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9337833643699565

In [24]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9332029795158288

In [25]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9449006828057108

# Exercise

In [27]:
from sklearn.datasets import load_iris
iris = load_iris()

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [29]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

1.0

In [30]:
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9666666666666667

In [33]:
rf = RandomForestClassifier(n_estimators=10)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

1.0

In [34]:
from sklearn.model_selection import cross_val_score

In [42]:
lr = cross_val_score(LogisticRegression(solver='liblinear'),iris.data, iris.target, cv=3)
lr

array([0.96, 0.96, 0.94])

In [43]:
np.average(lr)

0.9533333333333333

In [44]:
svm = cross_val_score(SVC(gamma='auto'), iris.data, iris.target, cv=3)
svm

array([0.98, 0.98, 0.96])

In [45]:
np.average(svm)

0.9733333333333333

In [46]:
rf = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target,cv=3)
rf

array([0.98, 0.94, 0.94])

In [47]:
np.average(rf)

0.9533333333333333